version: "3.7"
x-db-envvars: &db-envvars
  POSTGRES_DB: postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
x-default-envvars: &default-envvars
  <<: *db-envvars
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: "./Dockerfile"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      <<: *default-envvars
      COMPOSE_HTTP_TIMEOUT: 120
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
  backend:
    build:
      context: ./backend
      dockerfile: "./Dockerfile"
    volumes:
      - ./backend/:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      <<: *default-envvars
      COMPOSE_HTTP_TIMEOUT: 120
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "6432:5432"
    volumes:
      - transcendence:/var/lib/postgresql/data
    environment:
      <<: *db-envvars
      COMPOSE_HTTP_TIMEOUT: 120
  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"
    environment:
      COMPOSE_HTTP_TIMEOUT: 120
volumes:
  transcendence: