export enum AchievementType {
    FRESH_PADDLE = "FRESH_PADDLE",
    FIRST_VICTORY = "FIRST_VICTORY",
    PONG_WHISPERER = "PONG_WHISPERER",
	CHATTERBOX = "CHATTERBOX",
	SOCIAL_BUTTERFLY= "SOCIAL_BUTTERFLY",
	CHAMELEON_PLAYER= "CHAMELEON_PLAYER",
	// FRIENDLY_RIVALRY= "FRIENDLY_RIVALRY",
	EPIC_FAIL= "EPIC_FAIL"
  }